version: '3.7'

services:
  app_dev:
    build:
      context: .
      target: dev_env
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./go/src/goa_api/:/go/src/goa_api/
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_ja_0900_as_cs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080